#!/usr/bin/env node
/**
 * Inject the canonical footer (assets/footer.html) into every page.
 *
 * Why not the old runtime loader? assets/footer-loader.js fetched the
 * partial and assigned it with outerHTML. The partial was a complete HTML
 * document containing no <footer> element at all, so pages using the
 * loader rendered no footer whatsoever - locations.html shipped with zero
 * footer links. Runtime injection also keeps the footer out of the served
 * HTML, which costs SEO on a marketing site and causes a layout shift.
 *
 * Instead the footer is written into each page at build time, between
 * markers, so the shipped HTML is static and complete while there is still
 * a single source of truth.
 *
 * Usage
 *   node scripts/build-footer.mjs           inject / update
 *   node scripts/build-footer.mjs --check   verify pages are in sync (CI)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PARTIAL = join(ROOT, 'assets/footer.html');
const START = '<!-- FOOTER:START (generated by scripts/build-footer.mjs - do not edit) -->';
const END = '<!-- FOOTER:END -->';
const CHECK = process.argv.includes('--check');

// Directories whose pages get a footer, with the token values for each.
const TARGETS = [
  { dir: 'pages', pages: '', root: '../' },
  { dir: 'blog', pages: '../pages/', root: '../' },
  { dir: 'team', pages: '../pages/', root: '../' },
];

// Pages that deliberately have no footer. Empty: every page in the site now
// shares the single generated footer, including the admin/login screens.
const EXCLUDE = new Set([]);

function renderFooter(tokens) {
  let html = readFileSync(PARTIAL, 'utf8');
  html = html.replace(/<!--[\s\S]*?-->\n/, ''); // drop the partial's header comment
  return html.replace(/\{\{PAGES\}\}/g, tokens.pages)
             .replace(/\{\{ROOT\}\}/g, tokens.root)
             .trim();
}

/** Replace an existing footer (marked or unmarked) or insert before </body>. */
function applyTo(source, footerHtml) {
  const block = `${START}\n${footerHtml}\n${END}`;

  const marked = new RegExp(
    `${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`,
  );
  if (marked.test(source)) return source.replace(marked, block);

  if (/<footer[\s\S]*?<\/footer>/.test(source)) {
    return source.replace(/[ \t]*<footer[\s\S]*?<\/footer>/, block);
  }

  if (source.includes('</body>')) {
    return source.replace('</body>', `${block}\n</body>`);
  }
  return source + '\n' + block;
}

/** Pages that do not style .footer themselves need the shared stylesheet,
 *  otherwise the injected markup renders unstyled. Pages that already have
 *  their own footer CSS are left alone so nothing shifts visually. */
function ensureFooterCss(source, rootPrefix) {
  if (/footer\.css/.test(source)) return source;
  if (/\.footer\s*\{/.test(source)) return source; // already styled inline

  const link = `  <link rel="stylesheet" href="${rootPrefix}assets/footer.css">`;
  if (source.includes('</head>')) {
    return source.replace('</head>', `${link}\n</head>`);
  }
  return `${link}\n${source}`;
}

/** Remove the now-redundant runtime loader script tag. */
function stripLoader(source) {
  return source.replace(/[ \t]*<script[^>]*footer-loader\.js[^>]*>\s*<\/script>\r?\n?/gi, '');
}

let changed = 0;
let drifted = [];
let total = 0;

for (const target of TARGETS) {
  let entries;
  try {
    entries = await readdir(join(ROOT, target.dir), { withFileTypes: true });
  } catch {
    continue;
  }

  const footerHtml = renderFooter(target);

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.html')) continue;
    if (EXCLUDE.has(entry.name)) continue;

    const file = join(ROOT, target.dir, entry.name);
    const before = readFileSync(file, 'utf8');
    const after = ensureFooterCss(applyTo(stripLoader(before), footerHtml), target.root);
    total++;

    if (before === after) continue;

    if (CHECK) {
      drifted.push(relative(ROOT, file));
    } else {
      writeFileSync(file, after, 'utf8');
      console.log(`updated  ${relative(ROOT, file)}`);
      changed++;
    }
  }
}

if (CHECK) {
  if (drifted.length) {
    console.log('These pages are out of sync with assets/footer.html:\n');
    for (const f of drifted) console.log(`  ${f}`);
    console.log('\nRun: node scripts/build-footer.mjs');
    process.exit(1);
  }
  console.log(`All ${total} page footer(s) match assets/footer.html.`);
  process.exit(0);
}

console.log(`\n${changed} of ${total} page(s) updated.`);
